from PyQt6 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(160, 224)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(20, 140, 51, 23))
        self.startButton.setObjectName("startButton")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.verticalGroupBox.setGeometry(QtCore.QRect(10, 9, 141, 51))
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label1 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label1.setObjectName("label1")
        self.verticalLayout.addWidget(self.label1)
        self.label2 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label2.setObjectName("label2")
        self.verticalLayout.addWidget(self.label2)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.verticalGroupBox_2.setGeometry(QtCore.QRect(10, 70, 141, 61))
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton1 = QtWidgets.QRadioButton(self.verticalGroupBox_2)
        self.radioButton1.setObjectName("radioButton1")
        self.radioButton1.setChecked(True)
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton1)
        self.verticalLayout_2.addWidget(self.radioButton1)
        self.radioButton2 = QtWidgets.QRadioButton(self.verticalGroupBox_2)
        self.radioButton2.setObjectName("radioButton2")
        self.buttonGroup.addButton(self.radioButton2)
        self.verticalLayout_2.addWidget(self.radioButton2)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(90, 140, 51, 23))
        self.stopButton.setObjectName("stopButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(20, 170, 121, 23))
        self.exitButton.setObjectName("exitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Старт"))
        self.label1.setText(_translate("MainWindow", "TextLabel"))
        self.label2.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton1.setText(_translate("MainWindow", "Последовательно"))
        self.radioButton2.setText(_translate("MainWindow", "Параллельно"))
        self.stopButton.setText(_translate("MainWindow", "Стоп"))
        self.exitButton.setText(_translate("MainWindow", "Выход"))
